database:
    adapter: Mysql
    host: localhost
    username: root
    password:
    dbname:

application:
    controllerDir: app/controller/
    modelDir: app/model/
    viewsDir: app/views/
    layoutDir: app/views/
    formDir: app/form/
    cacheDir: app/cache/
    baseUri: /
    defaultNamespace: Young\Controller